version: '3'
services:
  web:
    image: haynesb/haynes-portfolio:${TAG}
    container_name: web_staging
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000

    environment:
        - DJANGO_SECURITY_KEY=${DJANGO_SECURITY_KEY}

