version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE=${MYSQL_DATABASE}
      MYSQL_USER=${MYSQL_USER}
      MYSQL_PASSWORD=${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
      # Where our data will be persisted
    volumes:
      - staging-db:/var/lib/mysql


  web:
    image: haynesb/haynes-portfolio:${TAG}
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000

    environment:
        - DJANGO_SECURITY_KEY=${DJANGO_SECURITY_KEY}

volumes:
  staging-db: