version: 2.1

orbs:
  python: circleci/python@1.5.0


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python manage.py test

          
  deploy-staging:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build and push Docker image
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker build -t haynesb/haynes-portfolio:$CIRCLE_TAG .
            docker push haynesb/haynes-portfolio:$CIRCLE_TAG
      - run:
          name: SSH in to DigitalOcean Server & Run Containers via Deploy.sh Script
          command: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "bash deploy-staging.sh $CIRCLE_TAG $DJANGO_SECURITY_KEY"
      


workflows:
  version: 2
  build:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: /.*/
      - deploy-staging:
          requires:
          - build-and-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+\.[0-9]+\.[0-9]+/
